"""Generate the client string tables from i18n/translations.py.

    python scripts/build_i18n.py          # write files
    python scripts/build_i18n.py --check  # exit 1 if the generated files are stale (used in CI)
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from i18n.translations import LANGS, table  # noqa: E402

TARGETS = {
    ROOT / "frontend/assets/js/i18n-strings.js": "window.GI_LANGS = {langs};\nwindow.GI_STRINGS = {strings};\n",
    ROOT / "mobile/src/strings.js": "export const LANGS = {langs};\nexport const STRINGS = {strings};\n",
}
HEADER = "// Generated by scripts/build_i18n.py from i18n/translations.py — do not edit by hand.\n"


def render(tpl: str) -> str:
    data = table()
    langs = json.dumps([{"code": c, "name": n} for c, n in LANGS], ensure_ascii=False)
    strings = json.dumps(data, ensure_ascii=False, indent=0, sort_keys=True)
    return HEADER + tpl.format(langs=langs, strings=strings)


def main() -> int:
    check = "--check" in sys.argv
    stale = []
    for path, tpl in TARGETS.items():
        text = render(tpl)
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                stale.append(path)
        else:
            path.write_text(text, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)} ({len(text) // 1024} KB)")
    if stale:
        print("stale:", *[str(p.relative_to(ROOT)) for p in stale], "— run python scripts/build_i18n.py")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
