"""initial schema

Revision ID: 9aec7b2a312c
Revises:
Create Date: 2026-10-06 06:26:49.347138

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9aec7b2a312c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_at'), ['at'], unique=False)

    op.create_table('data_sources',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('license', sa.String(length=128), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('records', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.Column('dataset', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_model_version')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('substations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('sheet', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('voltage_class_kv', sa.Integer(), nullable=False),
    sa.Column('data_status', sa.String(length=32), nullable=False),
    sa.Column('records', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('substation_id', sa.String(length=64), nullable=False),
    sa.Column('substation_name', sa.String(length=128), nullable=False),
    sa.Column('record_ts', sa.String(length=19), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_category', sa.String(length=16), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('parameter', sa.Text(), nullable=True),
    sa.Column('parameter_label', sa.Text(), nullable=True),
    sa.Column('equipment', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('signals', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['substation_id'], ['substations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('substation_id', 'record_ts', name='uq_alert_record')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_substation_id'), ['substation_id'], unique=False)

    op.create_table('anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('substation_id', sa.String(length=64), nullable=False),
    sa.Column('ts', sa.String(length=19), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('risk_category', sa.String(length=16), nullable=False),
    sa.Column('components', sa.JSON(), nullable=True),
    sa.Column('rules', sa.JSON(), nullable=True),
    sa.Column('model_key', sa.String(length=32), nullable=True),
    sa.Column('evaluation', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['substation_id'], ['substations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('substation_id', 'ts', name='uq_anomaly')
    )
    with op.batch_alter_table('anomalies', schema=None) as batch_op:
        batch_op.create_index('ix_anom_risk', ['risk_score'], unique=False)

    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('substation_id', sa.String(length=64), nullable=False),
    sa.Column('tag', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('voltage_kv', sa.Float(), nullable=True),
    sa.Column('rating_mva', sa.Float(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['substation_id'], ['substations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('substation_id', 'tag', 'kind', name='uq_equipment')
    )
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipment_substation_id'), ['substation_id'], unique=False)

    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('substation_id', sa.String(length=64), nullable=False),
    sa.Column('ts', sa.String(length=19), nullable=False),
    sa.Column('model_key', sa.String(length=32), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['substation_id'], ['substations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.create_index('ix_features_sub_ts', ['substation_id', 'ts'], unique=False)

    op.create_table('investigations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('substation_id', sa.String(length=64), nullable=False),
    sa.Column('record_ts', sa.String(length=19), nullable=False),
    sa.Column('author', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['substation_id'], ['substations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scada_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('substation_id', sa.String(length=64), nullable=False),
    sa.Column('ts', sa.String(length=19), nullable=False),
    sa.Column('parameter', sa.Text(), nullable=False),
    sa.Column('raw_value', sa.String(length=64), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('source_file', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['substation_id'], ['substations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scada_readings', schema=None) as batch_op:
        batch_op.create_index('ix_readings_sub_ts', ['substation_id', 'ts'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scada_readings', schema=None) as batch_op:
        batch_op.drop_index('ix_readings_sub_ts')

    op.drop_table('scada_readings')
    op.drop_table('investigations')
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.drop_index('ix_features_sub_ts')

    op.drop_table('features')
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_substation_id'))

    op.drop_table('equipment')
    with op.batch_alter_table('anomalies', schema=None) as batch_op:
        batch_op.drop_index('ix_anom_risk')

    op.drop_table('anomalies')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_substation_id'))

    op.drop_table('alerts')
    op.drop_table('substations')
    op.drop_table('users')
    op.drop_table('model_versions')
    op.drop_table('data_sources')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_at'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
